### ISSUE TITLE
Tsserver without rootDir

### ISSUE THREAD

**Issue by sarmong** [typescript-language-server/typescript-language-server#357] opened 2022-01-04 13:17 UTC
Is it technically possible to implement a feature that would allow this server to work on javascript files without the need for `jsconfig.json`?

E.g. assuming the default config option if the config is not present.

Sometimes I write little scripts in js or just use js file as a scratchpad and want lsp to work (I am using neovim)

**Comment by rchl** [comment] 2022-01-04 13:21
It already does work without explicit configuration. Maybe the issue is on the neovim side in that it requires tsconfig/jsconfig to be present?

**Comment by sarmong** [comment] 2022-01-04 13:58
Hm, I'll look into it, thanks

**Comment by DonnieWest** [comment] 2022-01-04 15:26
FWIW I use Neovim and I've almost never needed to configure a jsconfig.json

**Comment by sarmong** [comment] 2022-01-04 17:24
Apparently, the problem is not with `jsconfig`, but with `root_dir` parameter. Neovim doesn't find it (because there is no `package.json`, `tsconfig`, `jsconfig` or `.git` folder. 

Is this LSP or Neovim specific?

If LSP, then can current directory be considered `root` if none found?

**Comment by DonnieWest** [comment] 2022-01-04 18:14
Assuming you're using it, `nvim-lspconfig` indicates they don't officially support LSP servers that handle single files or projects without some form of root marker https://github.com/neovim/nvim-lspconfig/blob/b8ec1c50474af5eef45246f8324510a28db39bb0/doc/lspconfig.txt#L446-L471 . Other clients might have other limitations

I'm unsure if `typescript-language-server` has this limitation. I'd also hate for it to be something you rely on if it's really out of spec as `nvim-lspconfig` alleges :sweat_smile:

**Comment by rchl** [comment] 2022-01-04 18:47
Nor that this server didn't support single files before https://github.com/typescript-language-server/typescript-language-server/commit/fbf72dda58df6d485d86a7d38e8d64fc3903ea46 so it might be that the neovim client hasn't adapted to that change yet.

**Comment by DonnieWest** [comment] 2022-01-04 20:22
Since the problem lies outside of this project, closing this

**Closed by DonnieWest** 2022-01-04 20:22 UTC
