### ISSUE TITLE
missed ?.  and filterText

### ISSUE THREAD

**Issue by jadestrong** [typescript-language-server/typescript-language-server#631] opened 2022-11-22 15:25 UTC
steps to reproduce:
```typescript
interface Test {
    name?: string;
}

const t: Test = {};

t.name.
```

```json
[Trace - 09:12:59 PM] Sending request 'completionItem/resolve - (2105)'.
Params: {
  "label": "charAt",
  "kind": 2,
  "sortText": "11",
  "commitCharacters": [
    ".",
    ",",
    "("
  ],
  "data": {
    "file": "/Users/jadestrong/Documents/Github/typescript-language-server/src/completion.ts",
    "line": 43,
    "offset": 11,
    "entryNames": [
      "charAt"
    ]
  },
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 42,
        "character": 9
      },
      "end": {
        "line": 42,
        "character": 10
      }
    },
    "newText": "?.charAt"
  },
  "_emacsStartPoint": 1384
}


[Trace - 09:12:59 PM] Received response 'completionItem/resolve - (2105)' in 9ms.
Result: {
  "label": "charAt",
  "kind": 2,
  "sortText": "11",
  "commitCharacters": [
    ".",
    ",",
    "("
  ],
  "data": {
    "file": "/Users/jadestrong/Documents/Github/typescript-language-server/src/completion.ts",
    "line": 43,
    "offset": 11,
    "entryNames": [
      "charAt"
    ]
  },
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 42,
        "character": 9
      },
      "end": {
        "line": 42,
        "character": 10
      }
    },
    "newText": "charAt(${1:pos})$0"
  },
  "_emacsStartPoint": 1384,
  "detail": "(method) String.charAt(pos: number): string",
  "documentation": {
    "kind": "markdown",
    "value": "Returns the character at the specified index.\n\n*@param* `pos` — The zero-based index of the desired character."
  },
  "insertText": "charAt(${1:pos})$0"
}
```

![image](https://user-images.githubusercontent.com/18475217/203351860-5efec781-48bf-480d-8bd8-eabc15a24f9d.png)

Should the logic of `isMemberCompletion` and `dotAccessorContext` be added to return the filterText property?

https://github.com/microsoft/vscode/blob/6c866f92d7646c31bd9286b1cd8b8151c1e5b38e/extensions/typescript-language-features/src/languageFeatures/completions.ts#L100

**Comment by rchl** [comment] 2022-11-23 10:19
For what it's worth, my editor can't resolve completions before inserting them so I've never noticed this issue but I'm all for aligning with what VSCode does.

Not sure if we have as much context in LSP to solve it though. I suppose we might need to get text from the document to get the information that VSCode has in `completionContext`.

**Comment by rchl** [comment] 2023-02-08 23:03
Addressed in https://github.com/typescript-language-server/typescript-language-server/pull/678.

**Comment by rchl** [comment] 2023-02-10 21:40
I'm having second thoughts about this change because a lot of that logic seems to me to be a little too VSCode-centric and I'm not sure how does it help other editors.

Can you provide specific example where this change improves things in the editor you are using?

**Comment by jadestrong** [comment] 2023-02-11 03:44
I use Emacs and [lsp-mode](https://github.com/emacs-lsp/lsp-mode) where it use `filterText` or `label` if filterText not exist to filter completionItems, when encounter a optional field, the label is `charAt ` , but filterText should be `.?.charAt`.

https://github.com/emacs-lsp/lsp-mode/blob/781889628b9e0504fde279371548149deae4849d/lsp-completion.el#L264
In this case, because its filtering method does not consider the syntax of optional chain,  it will fail to filter

**Comment by jadestrong** [comment] 2023-02-11 03:50
If getFilterText is only used for vscode, this line may be removed?
https://github.com/typescript-language-server/typescript-language-server/blob/05f1dc46f7f9d6eab75c610e7723d9d1ea907967/src/completion.ts#L87 

But this line can be retained? https://github.com/typescript-language-server/typescript-language-server/blob/05f1dc46f7f9d6eab75c610e7723d9d1ea907967/src/completion.ts#L90

**Comment by jadestrong** [comment] 2023-02-11 04:12
For lsp-mode, it will guess the prefix, and then use the prefix to match the completion item for filtering.
When textEdit exist, it will use `range.start` as guess prefix' start point, then use `[start-point, current-point]` as prefix to match the completion item. For example:

```js
// input
t.name.cha
```

```js
// completionItem:
    {
      "label": "charAt",
      "filterText": ".?.charAt",
      "textEdit": {
        "range": {
          "start": {
            "line": 6,
            "character": 6
          },
          "end": {
            "line": 6,
            "character": 7
          }
        },
        "newText": "?.charAt"
      }
    },
```
startPoint is `(6, 6)` , prefix is `.cha`,  label is `charAt` ,missed the prefix `.` , so it will be filtered out.

**Comment by rchl** [comment] 2023-02-11 12:47
I still don't fully understand...

Are you saying that Emacs doesn't provide completion at all when `filterText` is missing in those cases or that it just scores them lower? Because in the case of VSCode that I've linked above it's about scoring higher and not about whether completion is present or not.

Also, why would the `filterText` be `.?.charAt` when the actual text to be replaced is `?.charAt`? And why editor logic uses `filterText` instead of just following `sortText` which is meant to be used for sorting?

**Comment by jadestrong** [comment] 2023-02-11 13:41
When `filterText` is missing, it will use `label` as `filterText`.
For lsp-mode, `filterText` is not used for sorting, but for filtering, it will cause all items to be filtered out.
As for why `.?.charAt`, that's because the input prefix is `.cha`, if the `.` is missed, the match will fail, because the first character must exist, otherwise it will be invalid when entering the first character. Of course, this is also the problem of its implementation algorithm

**Comment by jadestrong** [comment] 2023-02-11 13:45
If this change will affect other editors, you can revert it, I will think about how to change it in Emacs.

**Comment by rchl** [comment] 2023-02-11 13:54
> Of course, this is also the problem of its implementation algorithm

Yeah, it does seem like that since it's using filterText against the spec and even then requires quite a weird value that doesn't quite make sense (`.?.`).

I will think about it a bit more.
I would say that VSCode is also abusing `filterText` for its own purposes of improving sorting where it should be changing `sortText` instead...

**Comment by rchl** [comment] 2023-02-11 19:05
I've skimmed a bit too fast through your comments before.

From your great explanation of emacs behavior in https://github.com/typescript-language-server/typescript-language-server/issues/631#issuecomment-1426607617 above it looks like emacs would incorrectly filter out a perfectly valid completion like the one below because it doesn't include `filterText`:

```
    {
      "label": "charAt",
      "textEdit": {
        "range": {
          "start": {
            "line": 6,
            "character": 6
          },
          "end": {
            "line": 6,
            "character": 7
          }
        },
        "newText": "?.charAt"
      }
    },
```

This seems like a clear bug to me and adding `filterText` to workaround that shouldn't be needed and doesn't really make sense from the spec perspective.

And adding `filterText` like `.?.charAt` shouldn't bring any benefit to clients (even other than emacs) because it's not likely that user would type those extra `.` and `?` characters manually when typing `charAt`. This logic seems quite specific to VSCode where `filterText` can affect scoring/sorting but that again seems like a client-specific thing and really should be done with `sortText` instead. Ideally even at TypeScript level if it's deemed to be universally better.

(I'm saying all that to document the thinking rather than trying to convince you since you seem to understand and acknowledge some problems with the current emacs behavior.)

**Comment by rchl** [comment] 2023-02-12 21:32
Sorry but I've decided to revert the changes that set `filterText` based on comments above. https://github.com/typescript-language-server/typescript-language-server/pull/686

**Comment by jadestrong** [comment] 2023-02-12 23:11
OK，it doesn't matter

**Comment by yyoncho** [comment] 2023-02-17 11:18
@rchl when determining what to match against the client is supposed to use the range defined by textEdit if present and match it against the label/filterText. As described https://github.com/emacs-lsp/lsp-mode/issues/3961#issuecomment-1434481350 the prefix does not match the label, thus the completion item has to have filter text. You may refer to the discussion in  this issue: https://github.com/microsoft/language-server-protocol/issues/898

**Comment by yyoncho** [comment] 2023-02-17 11:43
To be a bit more specific: 

https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593968008 

> Completion Item with text edits: in this mode the server tells the client that it actually knows what it is doing. If you create a completion item with a text edit at the current cursor position no word guessing takes place and no filtering should happen. This mode can be combined with a sort text and filter text to customize two things. If the text edit can is a replace edit then the range denotes the word used for filtering. If the replace changes the text it most likely makes sense to specify a filter text to be used.

**Comment by rchl** [comment] 2023-02-17 13:00
I've made a comment about that recently in https://github.com/sublimelsp/LSP/issues/2189#issuecomment-1426896700 (you can read the whole thread if you have time).

I've commented on the part that you've quoted and it really confuses me. I don't think that's how it works right now even in VSCode. We could ask a clarifying question about that in the original issue or a new one.

I'm open to be proven wrong here and adjusting the behavior in ST LSP to accommodate for that but at this point I'm not convinced that the `filterText` is required to handle those completions properly. It's not a required field after all.

**Comment by ikapo** [comment] 2023-02-17 14:43
@rchl I agree with you that `filterText` is optional and that the Emacs lsp implementation needs to be changed to permit `filterText` to not be sent, but there's also some value in keeping it for compatibility, at least until an explanation is received from the quoted issue.
Would you be open to a PR where I revert `filterText` to be available again but under a configuration option which would be `false` by default (for performance)?

**Comment by yyoncho** [comment] 2023-02-17 14:47
> I've commented on the part that you've quoted and it really confuses me. I don't think that's how it works right now even in VSCode. We could ask a clarifying question about that in the original issue or a new one.

There is no need to ask questions, I tested it out: 

```
import java.util.con|
```

I invoked a completion against jdtls from this position and I received a mix of starting points positions depending on whether I am completing a class name or a namespace. Note that depending on how you pick the starting point on the client side for the completion you will either have false positive or false negative completion items. Thus you have to use `CompletionItem.textEdit.range.start` to get the start point when filtering out the completion items.


```
[Trace - 04:39:36 PM] Received response 'textDocument/completion - (260)' in 64ms.
Result: {
  "items": [
    {
      "label": "java.util.concurrent",
      "kind": 9,
      "detail": "(package) java.util.concurrent",
      "sortText": "999999215",
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "java.util.concurrent.${0:*};",
        "insert": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        },
        "replace": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        }
      },
      "data": {
        "pid": "0",
        "rid": "80",
        "uri": "file:///home/yyoncho/Sources/lsp/lsp-mode/test/fixtures/org-mode/java-project/src/main/java/temp/App.java"
      }
    },
    {
      "label": "java.util.concurrent.atomic",
      "kind": 9,
      "detail": "(package) java.util.concurrent.atomic",
      "sortText": "999999215",
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "java.util.concurrent.atomic.${0:*};",
        "insert": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        },
        "replace": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        }
      },
      "data": {
        "pid": "1",
        "rid": "80",
        "uri": "file:///home/yyoncho/Sources/lsp/lsp-mode/test/fixtures/org-mode/java-project/src/main/java/temp/App.java"
      }
    },
    ...
    ]
}
```

**Comment by rchl** [comment] 2023-02-17 14:48
It's an option to have it as a configuration yes (even if ideally this should work for everyone rather than be an option).

That said, this server never specified `filterText` (or if it did in the past then I don't remember it).

**Comment by yyoncho** [comment] 2023-02-17 14:50
Sorry, I deleted the wrong items for brevity, here it is the full response:

``` json
[Trace - 04:39:36 PM] Received response 'textDocument/completion - (260)' in 64ms.
Result: {
  "isIncomplete": false,
  "items": [
    {
      "label": "java.util.concurrent",
      "kind": 9,
      "detail": "(package) java.util.concurrent",
      "sortText": "999999215",
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "java.util.concurrent.${0:*};",
        "insert": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        },
        "replace": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        }
      },
      "data": {
        "pid": "0",
        "rid": "80",
        "uri": "file:///home/yyoncho/Sources/lsp/lsp-mode/test/fixtures/org-mode/java-project/src/main/java/temp/App.java"
      }
    },
    {
      "label": "java.util.concurrent.atomic",
      "kind": 9,
      "detail": "(package) java.util.concurrent.atomic",
      "sortText": "999999215",
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "java.util.concurrent.atomic.${0:*};",
        "insert": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        },
        "replace": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        }
      },
      "data": {
        "pid": "1",
        "rid": "80",
        "uri": "file:///home/yyoncho/Sources/lsp/lsp-mode/test/fixtures/org-mode/java-project/src/main/java/temp/App.java"
      }
    },
    {
      "label": "java.util.concurrent.locks",
      "kind": 9,
      "detail": "(package) java.util.concurrent.locks",
      "sortText": "999999215",
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "java.util.concurrent.locks.${0:*};",
        "insert": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        },
        "replace": {
          "start": {
            "line": 2,
            "character": 7
          },
          "end": {
            "line": 2,
            "character": 20
          }
        }
      },
      "data": {
        "pid": "2",
        "rid": "80",
        "uri": "file:///home/yyoncho/Sources/lsp/lsp-mode/test/fixtures/org-mode/java-project/src/main/java/temp/App.java"
      }
    },
    {
      "label": "ConcurrentModificationException - java.util",
      "kind": 7,
      "detail": "java.util.ConcurrentModificationException",
      "sortText": "999999372",
      "filterText": "ConcurrentModificationException;",
      "insertText": "ConcurrentModificationException",
      "insertTextFormat": 2,
      "textEdit": {
        "newText": "ConcurrentModificationException;",
        "insert": {
          "start": {
            "line": 2,
            "character": 17
          },
          "end": {
            "line": 2,
            "character": 20
          }
        },
        "replace": {
          "start": {
            "line": 2,
            "character": 17
          },
          "end": {
            "line": 2,
            "character": 20
          }
        }
      },
      "data": {
        "decl_signature": "Ljava.util.ConcurrentModificationException;",
        "pid": "3",
        "rid": "80",
        "uri": "file:///home/yyoncho/Sources/lsp/lsp-mode/test/fixtures/org-mode/java-project/src/main/java/temp/App.java"
      }
    }
  ]
}
```

**Comment by rchl** [comment] 2023-02-17 14:57
> There is no need to ask questions, I tested it out:

Sorry but I don't understand what does it prove exactly (I'm at work so maybe that's because I'm distracted)...

This could just be showing that the server knows that the context is `java.util.con` and returned completions that match that plus user prefix which in this case would be `con` (or `.con`) in case of ST (but should be universal for all editors).

All of those completions seem to be valid in this context and should be shown by the editor if the editor would just filter by `label` since the editor shouldn't need the prefix to match the start of the label but could be anywhere within the label.

**Comment by yyoncho** [comment] 2023-02-17 15:08
The point is that if you write `java.util.util` you will end up with the prefix `util` which will match everything instead of nothing. 

> in case of ST (but should be universal for all editors)

That is incorrect - it is not universal. Just check how xml and html servers work. If you have `<tag|` the filter text for xml server is `<tag` and it is `tag` for the html.

**Comment by rchl** [comment] 2023-02-17 15:28
OK, I get your point now.

Though servers like this one and many other that I'm using daily would only provide the part after `java.util.` as a label. That server's behavior is quite weird if you ask me.

That said, do you have a way of testing how would VSCode behavior when given this completion:

```
    {
      "label": "charAt",
      "textEdit": {
        "range": {
          "start": {
            "line": 6,
            "character": 6
          },
          "end": {
            "line": 6,
            "character": 7
          }
        },
        "newText": "?.charAt"
      }
    },
```

for text like:

```
'abcd'.c
```

Would it also not able to match the label? I would find it surprising if so.
I'm just trying if there is additional logic in this case that emacs is missing.

**Comment by yyoncho** [comment] 2023-02-17 15:47
The example you are providing is no different from the java completion result - just different values. So I would expect the same result - the client using CompletionItem.textEdit.range to determine the prefix. 

> I'm just trying to understand if there is additional logic in this case that emacs is missing.

Emacs is not missing logic - emacs has implemented completion and filtering after the reference client implementation - VScode. We had the ad-hoc solution that most of the clients had - just pick a random token and compare the results to it and it didn't work. Then we asked in the issue above how vscode is doing the filtering in the linked above issue and we ended up like that.

**Comment by jwortmann** [comment] 2023-02-18 05:38
> Would it also not able to match the label? I would find it surprising if so.

It would not match the label, but after re-reading the specs, I think this completion should still be shown, because

> If you create a completion item with a text edit at the current cursor position no word guessing takes place and no filtering should happen.

This also means that if you continue typing for example `'abcd'.const`, then the `charAt` completion should still be shown (!). This is also confirmed by the "foo-text-range-insert" example in https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593968008. In this case it probably makes sense to use a `CompletionList` with `"isIncomplete": true`, because it is assumed that all filtering happens on the server side. And I think even emacs does it wrong, based on
> When `filterText` is missing, it will use `label` as `filterText`.

(I see now that this was already described in https://github.com/typescript-language-server/typescript-language-server/issues/631#issuecomment-1426855439)

---

> So I would expect the same result - the client using CompletionItem.textEdit.range to determine the prefix.

No, if I understand it correctly, the prefix is irrelevant here, because there should be no filtering at all.

---

So I would say that typescript-language-server has the following options:
* do not specify `filterText` at all
* if it uses `filterText`, then it must include the prefix from the document starting at `CompletionItem.textEdit.range.start`, i.e. for the example including the leading `.`

And unfortunately, it doesn't seem to be possible in Sublime Text to accurately implement the LSP specs, because determing the prefix and the filtering happens in ST core, and the LSP client has no control over this. It can only choose the text which is filtered against (and at the same time displayed to the user in the completion popup).

**Comment by yyoncho** [comment] 2023-02-18 07:39
> > So I would expect the same result - the client using CompletionItem.textEdit.range to determine the prefix.
> 
> No, if I understand it correctly, the prefix is irrelevant here, because there should be no filtering at all.

@jwortmann the client is supposed to be able to cache the response when isIncomplete is false instead of calling the server on each key press. That is the whole point of having filterText...

**Comment by jwortmann** [comment] 2023-02-18 07:47
> @jwortmann the client is supposed to be able to cache the response when isIncomplete is false and filter client side instead of calling the server on each key press. That is the whole point of having filterText...

But the example you responded to *has no filterText*. This is the whole point of that example. And it's why I wrote that it makes sense to use `"isIncomplete": true` in this case.

**Comment by yyoncho** [comment] 2023-02-18 08:00
> > @jwortmann the client is supposed to be able to cache the response when isIncomplete is false and filter client side instead of calling the server on each key press. That is the whole point of having filterText...
> 
> But the example you responded to _has no filterText_. This is the whole point of that example. And it's why I wrote that it makes sense to use `"isIncomplete": true` in this case.

My comment is in general - filterText is included to support client-side filtering. So you cannot say that CompletionItem.textEdit.range is irrelevant. It may be irrelevant for the initial filtering but it is not for subsequent. I highly doubt that vscode does not filter the initial set if textEdit is present - I will test it out and report back. 

> This is also confirmed by the "foo-text-range-insert" example in https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593968008 

It is not - check the textEdit range in the example.

**Comment by rchl** [comment] 2023-02-18 08:39
I found it very easy to test VSCode with this simple example project: https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample

You can change the LSP server implementation easily and test various logic.

For example with completion implementation:

```
connection.onCompletion(
	(_textDocumentPosition: TextDocumentPositionParams): CompletionItem[] => {
		// The pass parameter contains the position of the text document in
		// which code complete got requested. For the example we ignore this
		// info and always provide the same completion items.
		return [
			{
				//filterText: '.foo',
				label: 'foo',
				kind: CompletionItemKind.Text,
				data: 1,
				textEdit: TextEdit.replace(Range.create(Position.create(0, 1), Position.create(0, 2)), '.bar')
			},
			{
				label: 'JavaScript',
				kind: CompletionItemKind.Text,
				data: 2
			}
		];
	}
);
```

I've confirmed that typing `a.f` at the start of the document doesn't show the first completion.

(Make sure that you test on a **saved** .txt file. I wasted time trying to get it to work before realizing that file has to be saved.

**Comment by jwortmann** [comment] 2023-02-18 08:46
> It is not - check the textEdit range in the example.

Right, I focused on whether `filterText` is present or not and didn't pay attention to the range.

So if I understand it correctly now, the crucial point how a client should decide whether to filter or not, is not the existence of `filterText`, but instead whether the `textEdit.range` is empty or not.

To be fair, the specs are written in a really imprecise way with no explanation of the used terms:

> a text edit at the current cursor position

actually means "a text edit with empty range", and

>If the text edit is a replace edit

means "If the text edit has a non-empty range", and "replace edit" has nothing to do with `InsertReplaceEdit`.

And it only makes sense to specify `filterText` in the latter case (if not present, use `label` instead for filtering).

**Comment by yyoncho** [comment] 2023-02-18 11:47
> So if I understand it correctly now, the crucial point how a client should decide whether to filter or not, is not the existence of `filterText`, but instead whether the `textEdit.range` is empty or not.

@jwortmann I believe that you always filter it is just that when the textEdit.range is empty you will have "" so filtering is no-op. I dont think that range = "" makes sense on any position but the cursor position.

**Comment by jwortmann** [comment] 2023-02-18 12:54
> I believe that you always filter [...]

Hm... if I look at this part of the specs, I would say that the last part of this sentence would contradict your assumption:
> **Completion Item with text edits**: in this mode the server tells the client that it actually knows what it is doing. If you create a completion item with a text edit at the current cursor position no word guessing takes place and no filtering should happen.

And also this part of the specs is even more explicit (emphasis by me):
> for speed clients should be able to filter an already received completion list if the user continues typing. **Servers can opt out of this** using a CompletionList and mark it as isIncomplete.

---

>  it is just that when the textEdit.range is empty you will have "" so filtering is no-op.

Well, my basic assumption about all of this is, that "filtering" means what happens if you continue typing. In other words, that some completion items are hidden if you type another letter, and if this new letter doesn't match those completion items anymore. Therefore the actual prefix used for filtering in this sense, is never empty.

The idea of an initial filtering (with empty or not empty prefix) before showing the items from the response, when the user has not typed any more letters yet, seems useless to me, because if there were items which would be filtered out, then why would the server have included them in the response at all? The server already knows the text to the left side of the cursor, so I would expect it to only return completions which makes sense in that context.

---

> My comment is in general - filterText is included to support client-side filtering.

I don't think that this is the purpose of `filterText`. Client-side filtering doesn't necessarily need the `filterText`, it has always worked also with `CompletionItem.label`, and even if the server doesn't provide any `filterText`. In the case of Sublime Text, there is even no way to opt-out of filtering.

Instead, I think the purpose of `filterText` is to allow to show something different in the completion popup, from what the editor internally uses for what the typed text is matched against. I have mentioned an example in https://github.com/sublimelsp/LSP/issues/2189#issuecomment-1435644535; in short the TexLab server uses the citation key of bibliography entries in the completion popup for brevity, but the user can type for example a book title or author if he doesn't remember the exact key.

**Comment by yyoncho** [comment] 2023-02-18 14:10
> Hm... if I look at this part of the specs, I would say that the last part of this sentence would contradict your assumption:

Unless I am mistaken @rchl confirmed that even for the first request, the filtering is performed, right? And yeah, there are servers that return an incomplete response with textEdits and that have to have their request filtered even on the initial run. I don't have these bug reports at hand because we fixed them about 2 years ago. Another thing is that it is not VScode that follows the spec. It is spec following VScode. If you discover something that vscode does not do by spec usually the devs fix the spec. And also, most of the server devs do not read the spec but they test what works with VScode. Obviously, I am not happy with that but this is how it is. 

> I don't think that this is the purpose of filterText. Client-side filtering doesn't necessarily need the filterText, it has always worked also with CompletionItem.label, and even if the server doesn't provide any filterText. In the case of Sublime Text, there is even no way to opt out of filtering.

I meant that filterText is needed for client-side filtering not that client-side filtering needs filterText to work. I think that we are on the same page here.

**Closed** 2023-02-20 13:07 UTC
Labels: enhancement
