### ISSUE TITLE
Question: Can typescript-language-server support imported types in JSDocs?

### ISSUE THREAD

**Issue by kevinfiol** [typescript-language-server/typescript-language-server#269] opened 2021-10-14 02:47 UTC
Note: Closed [this](https://github.com/sublimelsp/LSP-typescript/issues/94) issue because I think this is a more appropriate place for this question.

Hello! I love this project and how powerful it has made Sublime Text 4 for me. Kudos for the great work!

Recently, I began a JS-only project and decided to take advantage of defining my types via JSDocs. LSP-typescript works great for this. However, I became aware of another feature that allows types to be imported from an external types file via JSDocs. This allows for shorter comments and more expressive type definitions. See below for a screenshot of this working in VSCodium.

![image](https://user-images.githubusercontent.com/4752973/137242160-0b7cb365-9e56-4b31-9bd3-57b8bacb703e.png)

I'm wondering if such a feature is possible using Typescript Language Server? Frankly, I'm naive on whether this is more a VSCode thing or a TypeScript language server thing. Thanks for your time.

**Comment by rchl** [comment] 2021-10-15 07:59
The root issue could be the same as https://github.com/sublimelsp/LSP-volar/issues/38

If that's the case then it likely should be fixed in this server rather than the LSP client. I will test it out on Windows when I have some time.

**Comment by rchl** [comment] 2021-10-18 06:49
I can't reproduce it on my Windows system. Could you create a minimal repo that reproduces? Maybe tsconfig.json settings are relevant.

**Comment by rchl** [comment] 2021-10-31 06:56
I've created https://github.com/typescript-language-server/typescript-language-server/pull/276 to fix the issue with empty hover popup and https://github.com/typescript-language-server/typescript-language-server/pull/275 which might help with this issue but no guarantee since I can't reproduce it.

**Comment by rchl** [comment] 2021-11-03 20:50
I will tentatively resolve this since the fix that should help was released in https://github.com/typescript-language-server/typescript-language-server/releases/tag/v0.6.5

If that doesn't help then please provide a reproduction and we'll look further.

**Closed by rchl** 2021-11-03 20:50 UTC
