### ISSUE TITLE
Go to definition is not working on neovim

### ISSUE THREAD

**Issue by janoamaral** [typescript-language-server/typescript-language-server#795] opened 2023-11-12 01:17 UTC
In 4.1.0 go to `vim.lsp.buf.definition()` stop working. Rollback to 4.0.0 and works fine.

**Comment by rchl** [comment] 2023-11-12 08:53
You should provide LSP logs from the client

**Comment by rchl** [comment] 2023-11-13 19:45
Assuming it's a duplicate of #794

**Closed by rchl** 2023-11-13 19:46 UTC
