### ISSUE TITLE
Possible option to disable diagnostics service ?

### ISSUE THREAD

**Issue by vikigenius** [typescript-language-server/typescript-language-server#185] opened 2021-02-07 01:31 UTC
Hi, I am trying to use the following plugin: https://github.com/Quramy/typescript-eslint-language-service
with the typescript language server to get linting support.

But this causes errors to be reported twice. Does this server use eslint for diagnostics, does it support all the rules ?

I really like the completion provided by `typescript-language-server` but I would like to keep the linting provided by the plugin since eslint is the standard.

Is there a way to disable all diagnostics provided ?

See this issue for reference: https://github.com/emacs-lsp/lsp-mode/issues/1520

**Comment by nawordar** [comment] 2021-08-14 10:54
Related: #166

**Comment by rchl** [comment] 2021-08-18 07:29
Disabling all diagnostics wouldn't be a great solution for your problem IMO as only small amount of TS diagnostics have overlap with the eslint rules. You'd miss out on some important ones that eslint doesn't handle if you would do that.

Ignoring only certain diagnostics would probably make more sense in this case. But you'd need to maintain the list of ignores yourself.

**Comment by rchl** [comment] 2021-12-02 20:11
Duplicate of #209.

**Closed by rchl** 2021-12-02 20:11 UTC
