### ISSUE TITLE
LSP kind is changed after import

### ISSUE THREAD

**Issue by zer09** [typescript-language-server/typescript-language-server#419] opened 2022-03-14 02:40 UTC
Original issue https://github.com/hrsh7th/nvim-cmp/issues/838

I got a little concern about the autocomplete kind, when the function is not imported yet the lsp kind was able to detect that it was a function and will automatically import and add round brackets after the completion, but after it was successfully imported on the source and you will type the same function again the lsp kind will tell it just a variable and wont auto complete the round brackets.

Here is a sample screenshot
Before
![Screenshot_20220314_095045](https://user-images.githubusercontent.com/780780/158095566-59a0af26-01b9-44ce-8de4-973ae5c7bb95.png)

After import the `failedResult` should a function not a variable
![Screenshot_20220314_095315](https://user-images.githubusercontent.com/780780/158095572-c78cd8df-5ecf-4f5d-88fb-2c3a41a11f1d.png)

**Comment by rchl** [comment] 2022-03-21 08:29
If it behaves the same in VSCode then I would report this in the https://github.com/microsoft/TypeScript repo against VSCode since that would mean that the issue is in Typescript itself.

**Comment by rchl** [comment] 2022-05-14 21:43
I'll close this based on the explanation in the linked Typescript issue.

Even though I don't fully understand explanation provided there, the conclusion seems to be that it's either expected or should be handled different on the editor side. So it seems like the issue doesn't belong here.

**Closed by rchl** 2022-05-14 21:43 UTC
