### ISSUE TITLE
 FR for Autofix: Import all 

### ISSUE THREAD

**Issue by leomayer** [typescript-language-server/typescript-language-server#317] opened 2021-12-02 09:03 UTC
If I copy paste some code, e.g.
```
  @Input() ctrl: AbstractControl
```
I get an error since I won't have either `Input` nor `AbstractControl` imported yet. I can easily fix this by CTRL-Space and select the option. This has to be done on each of the statements.

It would be beneficial to have an option by which all the missing `import` would be inserted at once.

Followup of ticket from [wildwebdeveloper](https://github.com/eclipse/wildwebdeveloper/issues/743)

**Comment by rchl** [comment] 2021-12-02 14:55
Duplicate of #235.

**Closed by rchl** 2021-12-02 14:55 UTC
