### ISSUE TITLE
[Feature request] Project wide error handling

### ISSUE THREAD

**Issue by cybergazer** [typescript-language-server/typescript-language-server#923] opened 2024-10-12 22:14 UTC
Most other LSPs out there have project wide error handling built into Neovim, where you can see typescript errors in all subdirectories in quickfix. This features is extremely essential to any major Typescript project, it would be really nice to have it in ts_ls. So far it doesn't look like ts_ls has this and if it does it's too hard to use and no docs on it

**Comment by rchl** [comment] 2024-10-14 09:41
Duplicate of https://github.com/typescript-language-server/typescript-language-server/issues/358

**Closed by rchl** 2024-10-14 09:41 UTC
