### ISSUE TITLE
Incorrect TS7022 error displayed by Language Server in VSCode

### ISSUE THREAD

**Issue by martaver** [typescript-language-server/typescript-language-server#766] opened 2023-10-07 18:42 UTC
- VS Code Version: 1.83.0
- OS Version: MacOS Monterey 12.4 (but also shown in vscode on other MacOS versions)

Steps to Reproduce:

1. Clone https://github.com/cleric-sh/repro/tree/phantom-ts7022-error-in-vscode
2. Ensure switched to branch `phantom-ts7022-error-in-vscode`
3. `npm i`
4. `npm compile` --> observe no compiler errors
5. Open index.ts
6. Make a change to the file (e.g. add a space) to trigger LSP to re-analyse the file.
7. Restart the TS Language Server and error disappears. Make a change, and error re-appears.
8. Error should appear on `value` on line 26. 

The error appears with all extensions disabled.

I've noted that the error is:
- Only shown when func param 'arg' type is declared. Removing the declaration resolves the error.
- Only shown in vscode. tsc compiles without errors.
- Only shown on second pass, after a change has been made to the file. Initial type check on load shows no errors.
- Only shown when noImplicitAny: true
 
Also, in a more complex file, declaring this function after `doAnotherThing` prevents the error being displayed.

All these points combined lead me to believe this is an error either in VS Code or the Typescript Language Server.

I've also created an issue in the VSCode GitHub repo: https://github.com/microsoft/vscode/issues/195075

**Comment by martaver** [comment] 2023-10-07 18:51
I added `tsserver.log` to the repro, which covers starting TS Language Server and making a change to the file.

**Comment by martaver** [comment] 2023-10-07 19:19
Possibly related to issue: https://github.com/microsoft/vscode/issues/177595

**Comment by rchl** [comment] 2023-10-20 19:46
Based on the linked issue it seems like the issue was fixed in typescript.

**Closed by rchl** 2023-10-20 19:46 UTC

**Comment by rchl** [comment] 2023-10-23 19:02
It's not likely that this issue is in this server. I would suggest reporting it in the typescript repo since it reproduces with VSCode also which doesn't use this server.

**Comment by martaver** [comment] 2023-10-23 19:20
Tsc and ts playground don’t report the error. It’s only reproducible in
vscode and, presumably, probably with ts lang server. I couldn’t quite
figure out the ts server api to confirm, though…

What’s the point of taking the time to create a repro if nobody bothers to
open it?
