### ISSUE TITLE
Homebrew install

### ISSUE THREAD

**Issue by cloudlena** [typescript-language-server/typescript-language-server#241] opened 2021-07-30 11:03 UTC
It would be awesome if this language server could be installed via https://brew.sh/.

**Comment by rchl** [comment] 2021-07-30 11:42
It's a node package that can be installed with `npm install -g typescript-language-server` (you can install `node` itself from brew).

I don't think it would make sense to have as its own brew package since it needs to be installed within node. It probably wouldn't be even possible.

**Comment by mastertinner** [comment] 2021-07-30 11:47
The advantage of having it in Homebrew is that macOS users can install, update and manage all their tooling with a single tool. This makes life a lot easier than having to manage some things with `npm`, others with `cargo`, others with `brew`, others with `gem`, others with `pip` and so on.

Installing npm packages via Homebrew is definitely possible. Here's the example of `eslint`: https://formulae.brew.sh/formula/eslint#default

**Comment by rchl** [comment] 2021-11-13 20:21
Feel free to contribute a PR to add that. I think it should be doable with Github actions.

**Comment by lucario** [comment] 2022-03-06 00:48
typescript-language-server doesn't work with typescript installed from brew, you have to manually specify the tsserver path. I believe having the language server installed via brew might fix this. The alternative is to install typescript via npm globally. Also, the server can't find npm, you must manually specify that regardless for types caching.

**Comment by meengit** [comment] 2022-03-07 07:37
As far as I know, this depends on your environment settings. I mix NodeJS, TS, and this language server on several global and custom NodeJS environments without any issues in path resolution. Where are your "binaries" placed and and how are your environment settings for `node`, `npm`, `typescript` and `typescript-language-server`?

> The alternative is to install typescript via npm globally.

In my opinion, this is the perfect solution.

> I believe having the language server installed via brew might fix this.

I assume this causes a more complex situation, especially for dependency management. NodeJS and NPM (and global NodeJS modules) installed via "brew" may conflict with global installed NodeJS modules like typescript or this language server. How do you intend to keep them separated?

Of course, you can install ESLint via "brew." However, in my opinion:

* comparing ESLint with this language server is like comparing apples and oranges;
* except for some special use cases, its an anti-pattern.

**Comment by lucario** [comment] 2022-03-07 08:41
@meengit Those are excellent points and I am admittedly a novice in node.
```
2022-03-03 22:21:49.467: Server message: [lspserver] Using Typescript version (workspace) 4.6.2 from path "/Users/lucario/Developer/project/node_modules/typescript/lib/tsserver.js"
2022-03-03 22:21:49.737: Server message: [tsserver] /bin/sh: /opt/homebrew/Cellar/node/17.5.0/bin/npm: No such file or directory
```
Per the logs, it will use project typescript, and global npm correctly, however in both configurations, a manual symlink of npm is required for type caching. I try to use brew where I can to keep my packages in one place to reduce complexity and ease of upgrade; however brew seems to only increase complexity with dependency to node. I will switch to npm global typescript for now; unsure if the npm not found will be fixed ever. brew & npm global packages are in path.

**Comment by meengit** [comment] 2022-03-09 00:40
@lucario, well, I tried to reproduce your error. However, unfortunately, I was not able to. But this does not mean it does not exist. (I don't know if you are on a Mac, but I assume you are on an M1.)

If `node`, `npm`, and `typescript` are available when you start your default shell, I can only imagine your environment configuration (`.zshrc`, `.bashrc`, etc.) is not fully loaded when you try to start the language server. Otherwise, all brew packages should "see" each other (unless you use `brew unlink` or similar).

I know this effect from a situation where some of my coworkers accidentally tried to start a NodeJS program in a clean environment (in the sense of `env -i <command>`). But finally, these are all guesses. I hope you find a solution. If I gave you some advice, I would suggest: use `brew` for "finalized" programs like [`fx`](https://github.com/antonmedv/fx); load "development" tools always via their environment.

**Comment by adriantrunzo** [comment] 2024-03-08 18:17
There is a homebrew formula for the language server: https://formulae.brew.sh/formula/typescript-language-server. Looks like it was added to the registry about a year ago. I just installed the server via homebrew locally and have not run into any issues in my editor.

**Closed** 2024-03-09 15:33 UTC
Labels: enhancement, help wanted
