### ISSUE TITLE
Consumes too much memory

### ISSUE THREAD

**Issue by sarmong** [typescript-language-server/typescript-language-server#472] opened 2022-05-25 07:59 UTC
I have a very large project. I use neovim with native lsp and default configuration for tsserver.

I've noticed, that tsserver memory consumption is 1-2 gb, which is too much for comfortable work.

I opened vscodium to check if it consumes as much on the same project and no, it's less that 1 gb at most.

What could be the reason for this? I tried setting `maxTsServerMemory = 1024`, but it just makes the language server stop

![image](https://user-images.githubusercontent.com/42828375/170211615-394f6954-5d58-4ae2-9178-32cbeb0d179c.png)

**Comment by rchl** [comment] 2022-05-25 08:26
What are the arguments passed to those processes?

**Comment by sarmong** [comment] 2022-05-25 09:25
@rchl For some reason, I found two tsserver processes spawned by a single neovim instance.

![image](https://user-images.githubusercontent.com/42828375/170229276-6067b67a-3c1c-44d7-801f-2a63f98d8365.png)

Here are also process trees for reference:

![image](https://user-images.githubusercontent.com/42828375/170228916-dacfb16e-7794-49eb-b340-c02059ddcf3a.png)
![image](https://user-images.githubusercontent.com/42828375/170228967-425dd46a-f0cb-4c1a-a23d-901dbceeac98.png)

**Comment by rchl** [comment] 2022-05-25 11:07
Possibly different Typescript versions that are used different amount of memory. You could check inside both paths (in `node_modules/typescript/package.json` which versions are being used and try to match them.

**Comment by sarmong** [comment] 2022-05-25 11:47
Yes, vscodium uses `4.6.3`, whereas my project has `4.3.2`. 

Can I somehow make my neovim use the version of typescript I installed globally?

**Comment by rchl** [comment] 2022-05-25 11:54
I don't know how to configure neovim specifically but this server accepts `--tsserver-path` argument that can be used to force any version at given path.

By default it defaults to the version of Typescript included in the project as otherwise the results you see in editor might be different than when building the project, for example. So ideally the version of Typescript in the project should be updated.

**Comment by sarmong** [comment] 2022-05-25 12:13
I've updated local typescript version, but it didn't help. Still uses 1.4 gb of memory

**Comment by rchl** [comment] 2022-05-25 15:03
I suppose version of Node used could also make a difference. I suppose vscodium might be using v16 now.

Otherwise I'm not sure where would the difference come from. Since the arguments to tsserver are pretty close, there shouldn't be much if any difference if Node and Typescript versions are the same.

**Comment by rchl** [comment] 2022-06-06 20:08
Are you able to reproduce higher memory usage when testing on this repository, for example?

**Comment by sarmong** [comment] 2022-06-09 17:36
When I launch it with node 14.16, tsserver process takes *168mb*, when I launched it with node 16.15, it takes 208mb.

Tsserver instance spawned by VSCodium takes 143mb. Not a big of a difference, but it gets bigger with the size of the project, apparently

**Comment by rchl** [comment] 2022-07-24 15:48
I can confirm that tsserver started by this server uses 1.4GB when started on VSCode repo while VSCode uses 890MB

```
SUBLIME TEXT

26580 node
      cmd /Users/rafal/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node /Users/rafal/Library/Caches/Sublime Text/Package Storage/LSP-typescript/16.15.0/typescript-language-server/node_modules/typescript-language-server/lib/cli.js --stdio
      cwd /usr/local/workspace/github/vscode
      mem 41.1 MB

26582 node
      cmd /Users/rafal/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node /usr/local/workspace/github/vscode/node_modules/typescript/lib/tsserver.js --logVerbosity off --locale en --cancellationPipeName /private/var/folders/b0/93shkzpj2q39wrc0hhc22jbr0000gn/T/fe5a014e217c508dde28e77c0b935b64/tscancellation*
      cwd /usr/local/workspace/github/vscode
      mem 1.4 GB

26584 node
      cmd /Users/rafal/Library/Caches/Sublime Text/Package Storage/lsp_utils/node-runtime/16.15.0/node/bin/node /usr/local/workspace/github/vscode/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/rafal/Library/Caches/typescript/4.8 --typesMapLocation /usr/local/workspace/github/vscode/node_modules/typescript/lib/typesMap.json
      cwd /usr/local/workspace/github/vscode
      mem 33.4 MB

VSCODE

26453 Code Helper
      cmd /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/local/workspace/github/vscode/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/b0/93shkzpj2q39wrc0hhc22jbr0000gn/T/vscode-typescript501/7bb2fb028c7e8d785485/tscancellation-404e5eedce884ad74630.tmp* --logVerbosity verbose --logFile /Users/rafal/Library/Application Support/Code/logs/20220724T173844/exthost1/vscode.typescript-language-features/tsserver-log-Ra2b5a/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
      cwd /
      mem 167.2 MB

26454 Code Helper
      cmd /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /usr/local/workspace/github/vscode/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/b0/93shkzpj2q39wrc0hhc22jbr0000gn/T/vscode-typescript501/7bb2fb028c7e8d785485/tscancellation-2a444ba9e67f310ec1be.tmp* --logVerbosity verbose --logFile /Users/rafal/Library/Application Support/Code/logs/20220724T173844/exthost1/vscode.typescript-language-features/tsserver-log-zeh6x2/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
      cwd /
      mem 890.7 MB

26456 Code Helper
      cmd /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /usr/local/workspace/github/vscode/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/rafal/Library/Caches/typescript/4.8 --enableTelemetry --logFile /Users/rafal/Library/Application Support/Code/logs/20220724T173844/exthost1/vscode.typescript-language-features/tsserver-log-zeh6x2/ti-26454.log --typesMapLocation /usr/local/workspace/github/vscode/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
      cwd /
      mem 88.4 MB
```

VSCode starts server with those additional arguments:
 - `--useInferredProjectPerProjectRoot`
 - `--enableTelemetry`
 - `--noGetErrOnBackgroundUpdate`
 - `--validateDefaultNpmLocation`
 - `--useNodeIpc`

I've tried enabling all but the last one and it didn't make a change so it must be `--useNodeIpc`. Unfortunately implementing support for that would require quite a lot of work. And I'm not 100% sure if it would actually help or if there is something else going on here. I guess I could try to find VSCode version that didn't use `--useNodeIpc` yet and check that...

**Comment by rchl** [comment] 2022-07-24 15:58
OK, I've tested it in another way -- switched to TypeScript version 4.5.2 which doesn't support `useNodeIpc`. Results still show significantly more memory used by tsserver started by this server.
So I'm thinking now that VSCode's node runtime has some optimizations or just running with different flags which results in lower memory usage.

**Comment by rchl** [comment] 2022-07-24 16:43
Using VSCode's runtime does indeed make it match memory usage of VSCode...

**Comment by rchl** [comment] 2022-07-24 19:36
Digged deeper and apparently the reason for this is a feature called [Pointer Compression](https://github.com/nodejs/TSC/issues/790) that electron Enables when building Node.

I don't see a general solution for this issue apart from suggesting people to use Electron builds instead or building Node themselves. ;)

**Comment by rchl** [comment] 2022-07-24 20:03
With that said, it's not something that can be addressed in this project.

**Closed by rchl** 2022-07-24 20:03 UTC

**Comment by sarmong** [comment] 2022-07-25 09:04
Maybe instructions can be added to readme about using it with typescript-ls?

Also, does it affect the speed of the language server or just the memory usage?

**Comment by rchl** [comment] 2022-07-26 06:25
Feel free to suggest an edit that explains it. But note that this is not strictly specific to this project but to any project that uses node. Imagine if all Node-based projects in the world would have to separately document the same thing. :)

I've only tried on Mac and I did that by installing the `electron` dependency in a project or globally and then instead of starting using `node` to start the server I've used this binary: `/usr/local/workspace/github/typescript-language-server/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron` with `ELECTRON_RUN_AS_NODE=1` environment variable set.

According to https://v8.dev/blog/pointer-compression there should be no performance penalty or it should be at most very small. I've seen some people in the Node.js issue saying that it was slower in their use case but I have no any proof of that and it wouldn't necessarily apply in all cases anyway.

**Comment by sarmong** [comment] 2022-07-26 08:13
Is using Electron the only way? There should be some build flags to build node yourself.

Also, wondering how Webstorm does it, since this is not an electron based app

**Comment by rchl** [comment] 2022-07-26 08:24
Yes, there is a compile flag in Node:

```
./configure.py --experimental-enable-pointer-compression
make -j4
```

Don't know about Webstorm. Maybe ships its own build with it enabled.

**Comment by rchl** [comment] 2022-07-26 08:32
Webstorm appears to be using local Node from .nvm here:

![Screenshot 2022-07-26 at 10 31 29](https://user-images.githubusercontent.com/153197/180961371-0d966726-aeb3-4315-962c-2271f8dac9a9.png)

**Comment by ravi-dd** [comment] 2024-07-30 02:48
@sarmong wondering what you ended up doing.
